global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5000']

  - job_name: 'todo-app-health'
    metrics_path: /health
    static_configs:
      - targets: ['app:5000']


